name: Build and Deploy
on:
  # Trigger the workflow on push on the main branch
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to registry
        uses: docker/login-action@v2
        with:
          username: abarbier1
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            abarbier1/nft_api_listener-dev-service-image:${{ github.sha }}
            abarbier1/nft_api_listener-dev-service-image:latest
      - name: Display digest
        run: echo "🎉 Image built - ${{ steps.docker_build.outputs.digest }}"
  deploy:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: ./applications
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          repository: barterYard/BYC_ops
          token: ${{ secrets.PAC_GITHUB }}
      - uses: imranismail/setup-kustomize@v1
      - name: Kustomize
        run: kustomize edit set image abarbier1/nft_api_listener-dev-service-image:${{ github.sha }}
      - name: Commit files & push to ops
        run: |
          git config --global user.email "jarvis@barteryard.com"
          git config --global user.name "Jarvis"
          git add .
          git commit -m "bump nft_api_listener-dev-service-image to ${{ github.sha }}"
          git push
